/**
 * 4 PLAY · es-CO microcopy.
 *
 * Centralized so mobile + web stay in sync. Keep keys grouped by
 * surface (auth/profile/swipe/etc.) and avoid sprinkling user-facing
 * literals across screens.
 */
export const strings = {
  common: {
    cancel: 'Cancelar',
    accept: 'OK',
    close: 'Cerrar',
    retry: 'Reintentar',
    saving: 'Guardando…',
    loading: 'Cargando…',
    error: 'Algo salió mal',
  },
  auth: {
    onboardingKicker: 'CARTAGENA · 2026',
    onboardingTitleA: 'Encuentra ',
    onboardingTitleAccent: 'tu match',
    onboardingTitleB: ' en la cancha.',
    onboardingBody:
      'Tenis y pádel para la comunidad costera. Encuentra rivales de tu nivel, agenda canchas y juega más.',
    createProfile: 'Crear mi perfil',
    haveAccount: 'Ya tengo cuenta',
    loginKicker: 'INICIAR SESIÓN',
    loginTitle: '¿De vuelta?',
    loginBody: 'Entra para seguir jugando.',
    enter: 'Entrar',
    registerKicker: 'CREAR PERFIL',
    registerTitle: 'Empezamos.',
    registerBody: 'Tu email y una contraseña para entrar.',
    createAccount: 'Crear cuenta',
    needAccount: '¿No tienes cuenta?',
    needLogin: '¿Ya tienes cuenta?',
    confirmEmailNeeded: 'Te enviamos un correo para confirmar tu cuenta.',
    sessionExpired: 'Sesión vencida',
    pleaseLoginAgain: 'Vuelve a iniciar sesión.',
  },
  profileSetup: {
    stepLabel: (n: number) => `PASO ${n} DE 3`,
    titles: ['Tu identidad', 'Sobre ti', 'Tu juego'] as const,
    fullName: 'Nombre completo',
    username: 'Username',
    birthdate: 'Fecha de nacimiento (opcional)',
    neighborhood: 'Barrio',
    city: 'Ciudad',
    bio: 'Bio (máx 280)',
    locationCapture: 'Capturar ubicación para matchmaking',
    locationCaptured: (lat: number, lon: number) =>
      `Ubicación capturada (${lat.toFixed(3)}, ${lon.toFixed(3)})`,
    sport: 'DEPORTE',
    levelLabel: (level: number) => `NIVEL · ${level.toFixed(1)}`,
    yearsPlaying: 'Años jugando',
    next: 'Siguiente',
    back: 'Atrás',
    finish: 'Empezar',
    invalidUsername: 'Username inválido (3-32 minúsculas/números/_)',
    invalidDate: 'Fecha en formato YYYY-MM-DD',
    invalidBio: 'Bio máximo 280 caracteres',
    invalidSport: 'Deporte inválido',
    invalidLevel: 'Nivel entre 1.0 y 7.0',
    needName: 'Tu nombre es requerido',
  },
  swipe: {
    needsLocationTitle: 'Activa tu ubicación',
    needsLocationBody: 'Necesitamos saber dónde juegas para encontrar rivales cerca.',
    emptyTitle: 'No hay más jugadores cerca',
    emptyBody: 'Prueba aumentar el radio o cambiar de deporte en filtros.',
    refresh: 'Refrescar',
    matchKicker: '¡MATCH!',
    matchTitleA: 'Es ',
    matchTitleAccent: 'recíproco',
    matchTitleB: '.',
    matchBody: 'Conversa, agenden la cancha y a jugar.',
    startChat: 'Iniciar chat',
    keepBrowsing: 'Seguir buscando',
  },
  chat: {
    listKicker: 'CONVERSACIONES',
    listTitle: 'Tus matches',
    emptyTitle: 'Aún no hay matches',
    emptyBody: 'Empieza a hacer swipe para conocer jugadores cerca tuyo.',
    placeholder: 'Escribe un mensaje…',
    typing: '● ESCRIBIENDO…',
    online: '● ACTIVO',
    offline: '○ FUERA',
    startConversation: 'Empieza la conversación',
  },
  bookings: {
    listKicker: 'AGENDAR',
    listTitle: 'Canchas en Cartagena',
    emptyBody: 'No hay canchas en este radio. Aumenta el radio en filtros.',
    available: 'DISPONIBLE',
    consult: 'CONSULTAR',
    sectionTitle: 'Nueva reserva',
    day: 'Día',
    startHour: 'Hora de inicio',
    duration: 'Duración',
    book: 'Reservar y pagar',
    bookHint: 'La reserva queda en pending hasta confirmar el pago en Wompi.',
    invalidDate: 'No puedes agendar en el pasado.',
  },
  paywall: {
    badge: '4 PLAY+',
    titleA: 'Juega más,',
    titleAccent: 'conecta más.',
    body: 'Una membresía simple para todos los jugadores de Cartagena. Sin contrato, cancela cuando quieras.',
    monthly: 'MENSUAL',
    price: '$20.000',
    priceUnit: 'COP / mes · sin contrato',
    trial: '7 DÍAS GRATIS',
    benefits: [
      'Matches ilimitados con jugadores de tu nivel',
      'Reserva canchas en 14 clubes de la ciudad',
      'Chat directo y agenda compartida',
      'Ranking y stats de tus partidos',
    ] as const,
    cta: 'Empezar prueba gratis',
    afterTrial: 'DESPUÉS $20.000/MES · CANCELA EN 1 TOQUE',
  },
  settings: {
    title: 'Ajustes',
    account: 'Cuenta',
    accountSub: 'email, contraseña, datos personales',
    notifs: 'Notificaciones',
    notifsSub: 'matches, mensajes, recordatorios',
    privacy: 'Privacidad',
    privacySub: 'visibilidad, bloqueos',
    terms: 'Términos',
    termsSub: 'reglas de uso',
    privacyPolicy: 'Privacidad',
    privacyPolicySub: 'cómo manejamos tus datos',
    support: 'Soporte',
    supportSub: 'ayuda · contacto',
    pause: 'Pausar mi perfil',
    pauseConfirmTitle: 'Pausar perfil',
    pauseConfirmBody: 'Tu perfil dejará de aparecer en swipe. Puedes reactivarlo cuando quieras.',
    pausedDone: 'Tu perfil quedó en pausa.',
    logout: 'Cerrar sesión',
    logoutConfirmTitle: 'Cerrar sesión',
    logoutConfirmBody: '¿Seguro que quieres salir?',
  },
  report: {
    title: 'Reportar',
    body: 'Tu reporte es anónimo. Lo revisamos en menos de 24 horas.',
    extraLabel: 'Contexto adicional (opcional)',
    extraPlaceholder: 'Cuéntanos lo que pasó…',
    submit: 'Enviar reporte',
    sentTitle: 'Reporte enviado',
    sentBody: 'Gracias por avisarnos. Lo revisaremos pronto.',
  },
} as const;

export type StringPaths = typeof strings;
